Inmeso-Algorithm/Algorithm-Study

kuyho.chung/3213_피자.cpp
아래 과정을 통한 그리디 메소드를 통해 풀었습니다.
* 먼저 피자 1/2조각을 먹는 사람들의 수를 셈
* 다음, 피자 3/4조각을 먹는 사람들과 1/4조각을 먹는 사람들이 매칭되는 수를 셈
* 다음, 피자 1/2조각을 먹는 사람들의 수와 1/4조각을 먹는 사람 둘이 매칭되는 수를 셈
* 나머지 피자 1/4조각을 먹는 수를 셈
=> 3213_피자.cpp

admin/PR_rules.md
fixed table format and added kakao blind recruitment test's questions
=> updated readme

kuyho.chung/주사위 굴리기.cpp
단순 구현 문제입니다.
주사위를 전개도를 기준으로 상, 하, 좌, 우로 굴렸을 때 생기는 면의 변화를 하드코딩으로 구현하였습니다.
=> 14499 - 주사위 굴리기

kuyho.chung/문자열 압축.cpp
카테고리: 문자열, 브루트포스
먼저 변수 2개를 둡니다.
* length: 입력 문자열 s의 길이
* answer: 압축한 문자열의 길이를 담는 변수
다음으로, for문을 i = 1; i < length / 2 + 1로 돌면서 아래를 수행합니다.
* 이는, 반복되는 문자열 덩어리는, 반복된다면 최대 크기가 s의 길이의 절반이 되기 때문입니다.
* 이 기준에 따라, 이전 문자열 덩어리는 prev = substr(0,i)로 구해집니다.
* for문을 j = i; j < length; j += i로 반복하며 아래를 수행합니다.
* prev과 next가 같을 때마다 cnt값을 늘입니다.
* 그렇지 않다면, cnt값을 앞에 적고, prev를 이어 기록한 후, prev = next로 치환합니다.
위 과정을 통해, 길이 1 ~ s/2까지 반복되는 모든 경우에 대해 문자열을 압축하고, 그 결과를 answer에 최저값으로 갱신합니다.
=> 프로그래머스 - 문자열 압축

kuyho.chung/20925_메이플스토리.cpp
DP를 이용하여, 전날까지의 최적 경험치와 새로 추가될 사냥터의 경험치를 비교하며 풀었습니다.
=> 20925_메이플스토리

yunseong.oh/3213_피자.py
=> init commit

README.md
=> 18주차 문제 추가

kuyho.chung/19236_청소년 상어.cpp
* 기존에 사용하던 ```pair<int, int>``` 를 이용하여 좌표를 기록하던 방법 대신, x, y좌표에 더해 ```boolean``` 형식의 ```is_dead```를 추가한 struct를 정의하여 사용
* 주어진 조건을 dfs를 이용하여, 가장 큰 값을 찾아 나감
=> 19236_청소년 상어

README.md
=> 19주차 문제 추가

kuyho.chung/10974_모든 순열.cpp
순열 (permutation) 은 중복을 허용하지 않고 특정 수를 줄세울 수 있는 모든 경우의 수를 뜻함.
따라서 중복을 걸러내기 위하여 ```unordered_set```을 사용함.
생성된 순열 원소를 ```set```에 넣어 정렬된 상태로 저장되도록 함.
=> 10974_모든 순열

README.md
20주차 문제를 추가하였습니다.
* 테트로미노
* 로봇 청소기
* 감시 피하기
* 마법사 상어와 파이어볼
=> 20주차 문제 추가

kuyho.chung/18428_감시 피하기.cpp
전체 좌표를 corridor라는 2차원 배열에 담습니다. 선생님과 빈 공간의 위치는 각자 별도 배열에 저장합니다.
dfs를 통해 경우의 수를 탐색합니다. 장애물을 3개 세우는 모든 경우를 dfs를 통해 만들고, 만들었을 때 감시를 피할 수 있는지 확인합니다.
=> 18428_감시 피하기

Jiwon Choi/14500_테트로미노.py
=> 14500_테트로미노.py

Jiwon Choi/14499_주사위_굴리기.py, Jiwon Choi/14503_로봇 청소기.py, Jiwon Choi/16236_아기상어.cpp, Jiwon Choi/1931_회의실 배정.py, Jiwon Choi/2470_두 용액.py, Jiwon Choi/3213_피자.py, Jiwon Choi/7576_토마토.py, Jiwon Choi/문자열_압축.py
=> 14503_로봇 청소기.py

README.md
다음 네 개의 문제를 추가하였습니다.
- 25206: 너의 평점은
- 25212: 조각 케이크
- 2352: 반도체 설계
- 20057: 마법사 상어와 토네이도
[2022 인하대학교 프로그래밍 경진대회 (IUPC)](https://www.acmicpc.net/contest/view/780) 문제를 일부 포함하였습니다.
=> 21주차 문제 추가

kuyho.chung/25206_너의 평점은.cpp
단순 구현 문제입니다.
과목 이름은 중복되는 경우가 없으므로 별도로 저장하지 않았습니다.
=> 25206_너의 평점은

Jiwon Choi/20056_마법사 상어와 파이어볼.py
3차원 배열을 만들고 파이어볼이 한 공간에 여러 개 넣게 된다면 위쪽으로 쌓아 올라가는 형태로 구현하였습니다
=> 20056_마법사 상어와 파이어볼.py

kuyho.chung/25212_조각 케이크.cpp
원소수 1 ~ n개를 갖는 모든 부분집합을 dfs를 이용해 찾았습니다.
이미 방문한 위치는 unordered_set에 기록하여 다시 방문하지 않도록 했습니다.
완성된 부분집합은 문제의 케이크 한 판의 조건을 만족하는지 확인 후, 만족하는 경우 정답 카운트를 하나씩 증가시켰습니다.
=> 25212_조각 케이크

kuyho.chung/1016_제곱 ㄴㄴ 수.cpp
에라스토테네스의 채를 응용하여 풀었습니다.
숫자의 범위가 최대 1조이지만, 탐색해야 하는 숫자의 범위는 100만개 이내라는 점에 주목했습니다.
=> 1016_제곱 ㄴㄴ 수

README.md
=> 25주차 문제 추가

README.md, kuyho.chung/11404_플로이드.cpp
백준 11404번 문제 플로이드 풀이
+ 25주차 문제 목록 중 '단어 섞기' 링크가 동작하지 않아 수정하였습니다.
=> 11404_플로이드

kuyho.chung/10830_행렬 제곱.cpp
B가 짝수일 경우, A를 제곱하고, B가 홀수일 경우, ans와 A를 곱하는 식으로 진행했습니다.
B가 최대 1000억이므로, 37번 이내의 계산으로 답을 구할 수 있습니다.
=> 10830_행렬 제곱

kuyho.chung/9177_단어 섞기.cpp
글 https://velog.io/@embeddedjune/%EC%95%8C%EA%B3%A0%EB%A6%AC%EC%A6%98-%EB%B0%B1%EC%A4%80-DP-9177-%EB%8B%A8%EC%96%B4-%EC%84%9E%EA%B8%B0 를 참고하였습니다.
DP를 이용하여 풀었습니다.
i + j번째 자리의 글자가 a의 i번째 혹은 b의 j번째 글자와 같지 않다면, 단어를 만들 수 없습니다.
같다면, 이전에도 같았다면 만들 수 있고, 그렇지 않다면 만들 수 없습니다.
=> 9177_단어 섞기

kuyho.chung/14503_로봇 청소기.cpp
=> 14503_로봇 청소기

README.md
26주차 문제를 추가하였습니다.
* 5052. 전화번호 목록
* 1786. 찾기
* 1939. 중량제한
* 21611. 마법사 상어와 블리자드
=> 26주차 문제 추가

kuyho.chung/5052_전화번호 목록.cpp
문자열 기준으로 정렬한 후, i번째 원소가 i+1의 부분문자열인 경우가 하나라도 존재하면 NO를 출력하였습니다.
그렇지 않은 경우 탐색이 끝난 후 YES를 출력하였습니다.
=> 5052_전화번호 목록

kuyho.chung/21608_상어 초등학교.cpp
단순 구현 문제입니다.
학생을 위치할 빈칸 후보를 벡터에 넣은 후, 문제에서 제시한 조건을 연산 함수로 구현한 후 sort에 사용하였습니다.
=> 21608_상어 초등학교

README.md
27주차 문제를 아래와 같이 추가하였습니다.
* 15685. 드래곤 커브
* 1786. 감시
* 23288. 주사위 굴리기
* 23290. 마법사 상어와 복제
=> 27주차 문제 추가

README.md
28주차 문제를 추가하였습니다.
* 새로운 게임 2
* 여행 가자
* 저울
* 어드벤처 게임
=> 28주차 문제 추가

Jiwon Choi/1976_여행 가자.py
=> 1976_여행 가자.py

README.md
29주차 문제를 추가하였습니다.
이번 주 문제는 전부 카카오 블라인드 공채 코딩테스트 기출 문제입니다.
=> 29주차 문제 추가

README.md
=> 30주차 문제 추가

yunseong.oh/2178_미로.py, yunseong.oh/25206_너의평점은.py, yunseong.oh/3213_피자.py
=> Python 풀이 3문제 

README.md
31주차 문제를 추가하였습니다.
전부 카카오 블라인드 기출 문제입니다.
=> 31주차 문제 목록 추가

kuyho.chung/메뉴 리뉴얼.cpp
* 재귀를 사용해 가능한 부분집합을 구성합니다.
* unordered_set을 이용해 중복을 검사합니다.
=> 프로그래머스 - 메뉴 리뉴얼

kuyho.chung/순위 검색.cpp
=> 프로그래머스 - 순위 검색

README.md
32주차 문제들을 추가하였습니다.
백준에서 골드 레벨의 문제들로 구성하였습니다.
=> 32주차 내용 추가

kuyho.chung/11657_타임머신.cpp
=> 11657_타임머신

kuyho.chung/1167_트리의 지름.cpp
DFS를 이용하여 풀었습니다.
- DFS를 이용하여 root로부터 가장 먼 노드를 구함
- 가장 먼 노드로부터 가장 먼 노드까지의 거리를 구함
- 해당 거리가 정답
=> 1167_트리의 지름

kuyho.chung/11066_파일 합치기.cpp
DP를 이용하여 풀었습니다.
3중 for문을 사용했습니다.
- range: 찾아볼 숫자의 범위. 1: 1 ~ 2, 2 ~ 3, ...
- start: dp의 시작점
- div: 중간으로 나누는 지점
=> 11066_파일 합치기

README.md
=> 33주차 문제 목록 추가

kuyho.chung/1918_후위 표기식.cpp
stack을 이용하여 풀었습니다.
- 피연산자는 그대로 출력한다.
- 연산자인 경우,
- 스택이 비었으면 그대로 push
- 스택의 top이 현재 연산자보다 우선순위가 낮은 게 나올 때까지 pop
- 닫는 괄호 )의 경우, 여는 괄호 (가 나올 때까지 pop
=> 1918_후위 표기식

kuyho.chung/17182_우주 탐사선.cpp
플로이드-와셜 알고리즘과 DFS를 사용하였습니다.
- 플로이드-와셜을 사용하여 각 노드로부터 다른 노드까지의 최단거리를 구하여 기록
- DFS를 통해 모든 노드를 방문하는 경우의 수를 탐색 및 최단합거리 구하기
=> 17182_우주 탐사선

README.md
=> 34주차 문제 목록 추가
